name: Build, Test, and Release @caytu/shared

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install
      - run: yarn lint
      - run: yarn format:check

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup CodeArtifact registry
        id: codeartifact
        run: |
          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --query authorizationToken --output text)
          echo "CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> $GITHUB_OUTPUT
          npm config set "@caytu:registry" "https://caytu-${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.${{ secrets.AWS_REGION }}.amazonaws.com/npm/shared/"
          npm config set //caytu-${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.${{ secrets.AWS_REGION }}.amazonaws.com/npm/shared/:_authToken $CODEARTIFACT_AUTH_TOKEN

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Run type tests
        run: yarn test:types

      - name: Build
        run: yarn build

  create-release:
    needs: [lint-and-format, build-and-test]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Get current version
        id: current_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Determine new version
        id: new_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            NEW_VERSION=${GITHUB_REF#refs/tags/v}
          else
            NEW_VERSION=$(npx semver ${{ steps.current_version.outputs.VERSION }} -i patch)
          fi
          echo "VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update version if changed
        if: steps.current_version.outputs.VERSION != steps.new_version.outputs.VERSION
        run: |
          npm version ${{ steps.new_version.outputs.VERSION }} --no-git-tag-version
          git add package.json
          git commit -m "Bump version to ${{ steps.new_version.outputs.VERSION }} [skip ci]"
          git push
          git tag v${{ steps.new_version.outputs.VERSION }}
          git push --tags

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.new_version.outputs.VERSION }}
          release_name: Release ${{ steps.new_version.outputs.VERSION }}
          body: |
            Changes in this Release
            - Automated release by GitHub Actions
          draft: false
          prerelease: false

  publish:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup CodeArtifact registry
        id: codeartifact
        run: |
          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --query authorizationToken --output text)
          echo "CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> $GITHUB_OUTPUT
          npm config set "@caytu:registry" "https://caytu-${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.${{ secrets.AWS_REGION }}.amazonaws.com/npm/shared/"
          npm config set //caytu-${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.${{ secrets.AWS_REGION }}.amazonaws.com/npm/shared/:_authToken $CODEARTIFACT_AUTH_TOKEN

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish to AWS CodeArtifact
        run: npm publish

  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v3
