name: Build, Test, and Release @caytu/shared

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup CodeArtifact registry
        id: codeartifact
        run: |
          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --query authorizationToken --output text)
          echo "::set-output name=CODEARTIFACT_AUTH_TOKEN::$CODEARTIFACT_AUTH_TOKEN"
          npm config set "@caytu:registry" "https://caytu-${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.${{ secrets.AWS_REGION }}.amazonaws.com/npm/shared/"
          npm config set //caytu-${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.${{ secrets.AWS_REGION }}.amazonaws.com/npm/shared/:_authToken $CODEARTIFACT_AUTH_TOKEN

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Run type tests
        run: yarn test:types

      - name: Build
        run: yarn build

  create-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Get current version
        id: current_version
        run: echo ::set-output name=VERSION::$(node -p "require('./package.json').version")

      - name: Determine new version
        id: new_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            NEW_VERSION=${GITHUB_REF#refs/tags/v}
          else
            NEW_VERSION=$(npx semver ${{ steps.current_version.outputs.VERSION }} -i patch)
          fi
            echo ::set-output name=VERSION::$NEW_VERSION

      - name: Update version if changed
        if: steps.current_version.outputs.VERSION != steps.new_version.outputs.VERSION
        run: |
          npm version ${{ steps.new_version.outputs.VERSION }} --no-git-tag-version
          git add package.json
          git commit -m "Bump version to ${{ steps.new_version.outputs.VERSION }} [skip ci]"
          git push
          git tag v${{ steps.new_version.outputs.VERSION }}
          git push --tags

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.new_version.outputs.VERSION }}
          release_name: Release ${{ steps.new_version.outputs.VERSION }}
          body: |
            Changes in this Release
            - Automated release by GitHub Actions
          draft: false
          prerelease: false

  publish:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensure all history and tags are fetched
      - name: Fetch tags
        run: git fetch --tags

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup CodeArtifact registry
        id: codeartifact
        run: |
          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --query authorizationToken --output text)
          echo "::set-output name=CODEARTIFACT_AUTH_TOKEN::$CODEARTIFACT_AUTH_TOKEN"
          npm config set "@caytu:registry" "https://caytu-${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.${{ secrets.AWS_REGION }}.amazonaws.com/npm/shared/"
          npm config set //caytu-${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.${{ secrets.AWS_REGION }}.amazonaws.com/npm/shared/:_authToken $CODEARTIFACT_AUTH_TOKEN

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish to AWS CodeArtifact
        run: npm publish

      - name: Update README.md
        run: |
          sed -i "s|v[0-9]\.[0-9]\.[0-9]*|v${{ steps.new_version.outputs.VERSION }}|g" README.md
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update version in README.md to ${{ steps.new_version.outputs.VERSION }} [skip ci]"
          git push
